# Statistics

## Introductory R

## Advanced R

Other readings can include the RMarkdown and Bookdown readings:

[Xie, Dervieux & Riederer's \*'R Markdown Cookbook'\*]([https://bookdown.org/yihui/rmarkdown-cookbook/)](https://bookdown.org/yihui/rmarkdown-cookbook/)) and [Xie, Allaire & Grolemund's R Markdown: '\*The Definitive Guide'\*]([https://bookdown.org/yihui/rmarkdown/),](https://bookdown.org/yihui/rmarkdown/),)

[Xie's \*'bookdown'\*]([https://bookdown.org/yihui/bookdown/)](https://bookdown.org/yihui/bookdown/)) & [\*'blogdown'\*]([https://bookdown.org/yihui/blogdown/)](https://bookdown.org/yihui/blogdown/))

For a more advanced, serious education of R, I recommend learning in this order:

[Wickham and Grolemund's \*'R4DS'\*]([https://r4ds.had.co.nz/),](https://r4ds.had.co.nz/),)

[Douglas et al.'s '\*Intro2R'\*]([https://intro2r.com/),](https://intro2r.com/),)

[The official CRAN '\*Intro2R'\*]([https://cran.r-project.org/doc/manuals/r-release/R-intro.html),](https://cran.r-project.org/doc/manuals/r-release/R-intro.html),)

[Wickham's \*'Advanced R'\*]([https://adv-r.hadley.nz/)](https://adv-r.hadley.nz/))

(Optional) excellent R Bookdowns to read include:

[Lovelace, Nowosad & Muenchow's \*'Geocomputation in R'\*]([https://geocompr.robinlovelace.net/),](https://geocompr.robinlovelace.net/),)

[Wickham & Bryan's \*'R Packages'\*]([https://r-pkgs.org/),](https://r-pkgs.org/),)

[Jeroen Janssens's \*'DS at the CL'\*]([https://www.datascienceatthecommandline.com/1e/),](https://www.datascienceatthecommandline.com/1e/),)

[Fay et al.'s \*'Engineering Production-Grade Shiny Apps'\*]([https://engineering-shiny.org/)](https://engineering-shiny.org/))

## Introductory Statistical Programming

I've found [W. Chang's \*'Cookbook for R'\*]([http://www.cookbook-r.com/),](http://www.cookbook-r.com/),) [UCLA's Intro to R] [https://stats.oarc.ucla.edu/stat/data/intro_r/intro_r\_interactive_flat.html),](https://stats.oarc.ucla.edu/stat/data/intro_r/intro_r_interactive_flat.html),) & [BU's Basic Statistical Analysis]([https://sphweb.bumc.bu.edu/otlt/MPH-Modules/BS/R/R-Manual/R-Manual_print.html)](https://sphweb.bumc.bu.edu/otlt/MPH-Modules/BS/R/R-Manual/R-Manual_print.html)) the best single-page introduction for teaching R for statistics

Once you learn R and want a blend of R and statistical theory, [A. Swoeney's]([https://antoinesoetewey.com/)](https://antoinesoetewey.com/)) excellent ['Stats and R' Blogdown]([https://github.com/AntoineSoetewey/statsandr)](https://github.com/AntoineSoetewey/statsandr)) provides a PDF in ['What statistical test should I do?']([https://statsandr.com/blog/files/overview-statistical-tests-statsandr.pdf)](https://statsandr.com/blog/files/overview-statistical-tests-statsandr.pdf)) that users click the end-node links to follow.

More theory can be found at [\*Statistics for Biologists\*]([https://www.nature.com/collections/qghhqm)](https://www.nature.com/collections/qghhqm)) and its sub-page [\*Points of Significance\*]([https://www.nature.com/collections/qghhqm/pointsofsignificance)](https://www.nature.com/collections/qghhqm/pointsofsignificance))

[\*Handbook of Statistical Analyses Using R\* (HSAUR) 3rd ed.]([https://rdrr.io/cran/HSAUR3/)](https://rdrr.io/cran/HSAUR3/)) entirely available online as individual chapter PDFs, with the associated [HSAUR3]([https://cran.r-project.org/web/packages/HSAUR3/index.html)](https://cran.r-project.org/web/packages/HSAUR3/index.html)) package in CRAN with Vignettes and official documentation [reference manual]([https://cran.r-project.org/web/packages/HSAUR3/HSAUR3.pdf)](https://cran.r-project.org/web/packages/HSAUR3/HSAUR3.pdf))

## Intermediate Statistical Programming

Regression: I've struggled to find reputable open-sourced pages of regression education, let alone incorporation in R, but the [PSU STAT 501]([https://online.stat.psu.edu/stat501/)](https://online.stat.psu.edu/stat501/)) has caught my attention

Ecology statistics with [Oksanen's \*vegan\*]([https://github.com/vegandevs/vegan)](https://github.com/vegandevs/vegan)) [rdocumentation]([https://rdocumentation.org/packages/vegan)](https://rdocumentation.org/packages/vegan)) and [CRAN]([https://cran.r-project.org/web/packages/vegan/index.html)](https://cran.r-project.org/web/packages/vegan/index.html))

## Advanced Statistical Programming

High dimensional statistics can be learned from [Borg & Groenen's '\*Modern Multidmensional Scaling'\*]([https://link.springer.com/book/10.1007/0-387-28981-X)](https://link.springer.com/book/10.1007/0-387-28981-X))

## Data Visualization

Data visualization should use:

[Wickham's '\*ggplot2'\*]([https://ggplot2-book.org/),](https://ggplot2-book.org/),)

[Wilke's \*'Fundamentals of Data Visualization'\*]([https://clauswilke.com/dataviz/),](https://clauswilke.com/dataviz/),)

[W. Chang's \*'R Graphics Cookbook'\* 2e]([https://r-graphics.org/),](https://r-graphics.org/),) and

\*\*DEFINNITELY\*\* give the [ggplot2 extensions gallery]([https://exts.ggplot2.tidyverse.org/gallery/)](https://exts.ggplot2.tidyverse.org/gallery/)) a peak, that I most highly recommend Patil's [\*ggstatplot\*]([https://github.com/IndrajeetPatil/ggstatsplot/)](https://github.com/IndrajeetPatil/ggstatsplot/))
