# Structural Biology

Structural biology is The Holy Grail of pharmacology; the dynamic states of pharmacological target activation/inactivation as determined by receptor theory

## Cryogenic electronic microscopy (CryoEM)

The [Theoretical and Computational Biophysics Group (TCBG)]() provides [tutorial-based training]([https://www.ks.uiuc.edu/Training/Tutorials/)](https://www.ks.uiuc.edu/Training/Tutorials/)) and a database of software for 3D molecular [building]([https://www.ks.uiuc.edu/Development/biosoftdb/biosoft.cgi?&category=3),](https://www.ks.uiuc.edu/Development/biosoftdb/biosoft.cgi?&category=3),) [dynamics]([https://www.ks.uiuc.edu/Development/biosoftdb/biosoft.cgi?&category=2)](https://www.ks.uiuc.edu/Development/biosoftdb/biosoft.cgi?&category=2)) and [visualization]([https://www.ks.uiuc.edu/Development/biosoftdb/biosoft.cgi?&category=1)](https://www.ks.uiuc.edu/Development/biosoftdb/biosoft.cgi?&category=1))

Further resources can be found notably at the [EMBLI-EBI]([https://www.ebi.ac.uk/training/search-results?query=structural-biology),](https://www.ebi.ac.uk/training/search-results?query=structural-biology),) Stanford

The NIH established the following [CryoEM Centers]([https://www.cryoemcenters.org/cryoem-centers/)](https://www.cryoemcenters.org/cryoem-centers/)) through [awards]([https://www.nih.gov/news-events/news-releases/nih-funds-three-national-cryo-em-service-centers-training-new-microscopists)](https://www.nih.gov/news-events/news-releases/nih-funds-three-national-cryo-em-service-centers-training-new-microscopists)) to the

[National Center for CryoEM Access and Training (NCCAT)]([https://nccat.nysbc.org/)](https://nccat.nysbc.org/)) at the [New York Structural Biology Center (NYSBC)]([https://nysbc.org/),](https://nysbc.org/),) the

[Pacific Northwest Center for Cryo-EM]([https://pncc.labworks.org/)](https://pncc.labworks.org/)) at the [Pacific Northwest National Laboratory(PNNL)]([https://www.pnnl.gov/),](https://www.pnnl.gov/),) the

[Stanford-SLACC Cryo-EM Center]([https://cryoem-s2c2.slac.stanford.edu/)](https://cryoem-s2c2.slac.stanford.edu/)) at the [National Accelerator Laboratory]([https://www6.slac.stanford.edu/)](https://www6.slac.stanford.edu/))

\*\*Online learning resources include\*\*:

[Thermo Fisher's EM-Learning]([https://em-learning.com/)](https://em-learning.com/)) and

[CryoEM Learning Center]([https://www.thermofisher.com/us/en/home/electron-microscopy/life-sciences/learning-center.html)](https://www.thermofisher.com/us/en/home/electron-microscopy/life-sciences/learning-center.html)) by

[Grant Jensen, CalTech]([https://cryo-em-course.caltech.edu/),](https://cryo-em-course.caltech.edu/),) and

[Matthijn Vos, the Pasteur Institute]([https://research.pasteur.fr/en/team/nanoimaging/)](https://research.pasteur.fr/en/team/nanoimaging/))

[Yale CryoEM]([https://cryoem.yale.edu/cryo-em/workshops-and-online-courses),](https://cryoem.yale.edu/cryo-em/workshops-and-online-courses),)

[UNC CryoEM Core]([https://www.med.unc.edu/cryo-em/)](https://www.med.unc.edu/cryo-em/)) lists [resources available]([https://www.med.unc.edu/cryo-em/cryoem-links-and-resources/),](https://www.med.unc.edu/cryo-em/cryoem-links-and-resources/),) and

[NIGMS National Resource for Automated Molecular Microscopy (NRAMM)]([https://nramm.nysbc.org/workshops-and-courses/)](https://nramm.nysbc.org/workshops-and-courses/))

## X-Ray Crystallography
