---
editor_options: 
  markdown: 
    wrap: 72
---

------------------------------------------------------------------------

title: "A Minimal Book Example" author: "Jacob McPherson" date:
"`r Sys.Date()`" site: bookdown::bookdown_site documentclass: book
bibliography: [book.bib, packages.bib] url:
<https://jkmcpherson.netlify.app/> \# cover-image: path to the social
sharing image like images/cover.jpg description: \| This is a minimal
example of using the bookdown package to write a book. The HTML output
format for this example is bookdown::gitbook, set in the \_output.yml
file. link-citations: yes github-repo: jkmcpherson/jkmcpherson ---o

# Welcome!

Welcome to my homepage! I keep a lot more references than immediately
necessary, but it is my way of organizing my brain. This is a *Git Book*
written in *Markdown*, rendered in*Netlify*. We can insert equations,
such as $a^2 + b^2 = c^2$, links, or insert chunks of code from multiple
languages, such as R and python:

```{r eval=FALSE}
print("Hello world!")
```

```{python}
print("Hello world!")
```

## Book Sections

You can render the HTML version of this example book without changing
anything:

1.  Statistical Programming

2.  Scientific Programming

3.  Academic Programming

## Book Chapters

You can render the HTML version of this example book without changing
anything:

1.  Statistical Programming

|                             | R   | Python | Julia |
|-----------------------------|-----|--------|-------|
| Introductory                |     |        |       |
| Advanced                    |     |        |       |
| Data Science                |     |        |       |
| Data Visualization          |     |        |       |
| Fundamental Statistics      |     |        |       |
| High-dimensional Statistics |     |        |       |
| Artificial Intelligence     |     |        |       |
| Machine Learning            |     |        |       |
| Deep Learning               |     |        |       |

2.  Scientific Programming

| Category         | Theory | R   | Python | Commercial |
|------------------|--------|-----|--------|------------|
| **Genomics**     |        |     |        |            |
| Transcriptomics  |        |     |        |            |
| Proteomics       |        |     |        |            |
| Metabolomics     |        |     |        |            |
| **Pharmacology** |        |     |        |            |
|                  |        |     |        |            |
|                  |        |     |        |            |
|                  |        |     |        |            |
|                  |        |     |        |            |
|                  |        |     |        |            |
|                  |        |     |        |            |
|                  |        |     |        |            |
|                  |        |     |        |            |
|                  |        |     |        |            |
|                  |        |     |        |            |
